### ISSUE TITLE
sex of persons

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-SI/siParl#10]
Sem hotel javit oz. kar popravit na dihurju, pa je problem s povezavo oz. spletiščem, zato nadaljujem s poročanjem kar tule (kar je mogoče ok, ker je itak treba popravit ne samo tam, ampak tudi za siParl generirat nove kolofone):
* StarmanDanijel1940 ima 2x zapisan element `<sex value="M"/>`
* MakViljem1937 ima `<sex value="m"/>` namesto `<sex value="M"/>`

**Comment by andrejPancur** [comment]
Urejeno.
