### ISSUE TITLE
Madate overlap

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-SI/siParl#11]
Tudi pri mandatih je 1x prekriven datum, in sicer med  11. sklicem (1990-05-08 - 1992-12-23) in 1. mandatem (1992-12-23 - 1996-11-27). Sicer pa ni. Če se je pri madatih (in poslancih in njihovih članstvih v stankah) res dogajalo, da so prekrivni (verjetno se je, saj se niso točno ob polnoči premislili), bi vseeno svetoval, da so datumi disjunktni.

**Comment by andrejPancur** [comment]
Upošteval.
