### ISSUE TITLE
NO-BREAK SPACE

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-SI/siParl#2]
Moj program trenutno umre, če nabaše na segment brez pojavnic. Ravnokar je to storil na SDZ1/Izredna-07-1994-04-07.xml, ki vsebuje:

```
<seg xml:id="SDZ1-Izredna-07-1994-04-07.seg23"> </seg>
```
Vsebina tega segmenta (kar se mogoče zgoraj ne vidi) je U+00A0 NO-BREAK SPACE.
Če se pogleda https://clarin-eric.github.io/parla-clarin/#sec-chars tam piše, da naj se ta znak zamenja z navadnim space, kar bi bilo sigurno dobro narediti v siParl (trenutno se NO-BREAK SPACE pojavi 10.565 krat). Dodatno, da se segmenti, ki ne vsebujejo drugega kot presledke, brišejo (trenutno je 45 takih, ki vsebujejo samo NO-BREAK SPACE).

**Comment by andrejPancur** [comment]
Urejeno.
