### ISSUE TITLE
SOFT HYPHEN

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-SI/siParl#3]
Podobno kot za #2, omenja https://clarin-eric.github.io/parla-clarin/#sec-chars tudi U+00AD SOFT HYPHEN. Samo v tem primeru svetuje, da naj se kar zbriše.

siParl trenutno vsebuje ta znak 125x, 1x tudi kot edini znak v segmentu.

**Comment by andrejPancur** [comment]
Urejeno.
