### ISSUE TITLE
Taxonomy: Types of speakers

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-SI/siParl#4]
Taksonomija za vrste govornikov ima eno samo katerorijo, in sicer za Predsedujočega. Takšna taksonomija je po moje patološka, kar se potem vidi tudi pri govorih, kjer je so z `@ana` označeni samo predsedujoči, ostali nimajo tega atributa, kar bi pomenilo, da so neznana vrsta govornika (kar je deloma mogoče celo res, ker so v siParl 1.0 bili tako regularni, kot neavtorizirani govorci, in te razlike sedaj ni več). Vseeno, zdelo bi se mi bolj čisto, če bi se taksonomijo povečalo (predlog spodaj), in se potem povsod dalo `u/@ana`. Dodatno se mi ne zdi slabo, da ima vsaka taksonomija tudi ID.

```
<taxonomy xml:id="speaker_types">
   <desc xml:lang="en">Types of speakers</desc>
   <desc xml:lang="sl">Vrste govornikov</desc>
   <category xml:id="chair">
      <catDesc xml:lang="en"<term>Chairperson</term>: chairman of a meeting</catDesc>
      <catDesc xml:lang="sl"><term>Predsedujoči</term>: predsedujoči zasedanja</catDesc>
   </category>
   <category xml:id="regular">
      <catDesc xml:lang="en"><term>Regular</term>: a regular speaker at a meeting</catDesc>
      <catDesc xml:lang="sl"><term>Navadni</term>: navadni govorec na zasedanju</catDesc>
   </category>
</taxonomy>
```

**Comment by andrejPancur** [comment]
Urejeno. Moram samo še narediti pretvorbo drama2speech.
