### ISSUE TITLE
PodobnikMarijan MP overlap

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-SI/siParl#5]
`PodobnikMarjan` ima prekrivna termina, ko je bil MP: v prvi vrstici bi moral biti verjetno `to="1996-11-27"`:

```
<affiliation role="MP" ref="#DZ" from="1992-12-23" to="2000-06-13" ana="#DZ.1"/>
<affiliation role="MP" ref="#DZ" from="1996-11-28" to="2000-10-26" ana="#DZ.2"/>
```
PS: Mogoče je še kje napaka v datumih MP mandatov, bi se pa to dalo avtomatsko preverit, saj so pri affiliation datumi reduntantni (kar sicer ni slabo, da ni treba zasledovati kazalca v ana).

**Comment by andrejPancur** [comment]
Upošteval.
