### ISSUE TITLE
Short dates

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-SI/siParl#6]
V kolofonu so natanko trije datumi, kjer manjka dan, in sicer:

```
WARN: short date "1992-04"
WARN: short date "1992-05"
WARN: short date "1992-06"
```

Mogoče je to nanašč, ker se ne ve za točen datum, ampak, glede na to, da so samo trije (in 4 pojavitve, prvi 2x, ostali 1x), bi jaz skoraj navijal, da se jim kar da "-01" (v nasprotnem primeru ima xs:date probleme).

**Comment by andrejPancur** [comment]
Upošteval. Si naredil opombo v komentarju, če bi kasneje dobil pravilen datum in bi lahko popravil
