### ISSUE TITLE
čšž in filenames

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-SI/siParl#9]
Nekatere datoteke imajo v imenih čšž (npr. `KZPTZČPIEM-nujna-11-2015-06-30`). Imeti v imenih karkoli razen ASCII je precej nevarno, ker slej ko prej kakšen program to narobe interpretira. Meni žal že, in se potem mučim... Če ne bi bilo prehudo, bi zelo svetoval, da se take raje da v CSZ - kolikor sem videl, ne bi bilo konfliktov.
V resnici bi ta nasvet moral dati v https://clarin-eric.github.io/parla-clarin/#sec-files

**Comment by andrejPancur** [comment]
Urejeno v drama/. Moram nato samo še narediti novo pretvorbo drama2speech.
